[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
smart_contract = "DashYRE2h6KxNtm3mpss1u2xKNF5YxCqpv8LnXWJnyBp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "./keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
