[toolchain]

[features]
seeds = false
skip-lint = false

[programs.Devnet]
smart_contract = "DashYRE2h6KxNtm3mpss1u2xKNF5YxCqpv8LnXWJnyBp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/jianwei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
