[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
smart_contract = "7jKRsGXXckMtDpuUUsdxRrU8zaMohyXNKndET1Q8RmEi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/jianwei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
