[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
smart_contract = "D2BmD9mDRktiwF7rdjB6ePCq3VvdyoetQk1X7BomD16c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/jianwei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
